# "service" is the name of this project. This will also be added to your AWS resource names.
service: jeff
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1  # Specify your desired region
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:*"
      Resource: "*"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get